### ISSUE TITLE
duplicate actors - merging 2 entries

### ISSUE THREAD

**Issue by cvandeplas** [MISP/misp-galaxy#168]
How should we approach the situation where 2 entries in the threat-actors.json file should be merged to one single entry? 
Both already have a uuid.
Example:
- Callisto 
- Malware Reusers

**Comment by SteveClement** [comment]
@Delta-Sierra any thoughts on this?

**Comment by SteveClement** [comment]
@Delta-Sierra bump

**Comment by Delta-Sierra** [comment]
Ew, to be honest, I kind of always forget what is the best methodology.
But usually I try to merge both in the "biggest one" (the onea with most information). If both contains the same quantity of information, I usually merge them in the oldest (supposed to be the first in the galaxy).
But again, I can not say that it is the best way to proceed.
