### ISSUE TITLE
Duplicates in Pre Attack - Attack Pattern

### ISSUE THREAD

**Issue by Rafiot** [MISP/misp-galaxy#177]
There are 3 entries with the same value: "Analyze organizational skillsets and deficiencies"
2 with this one: "Identify business relationships"
2 with "Acquire and/or use 3rd party infrastructure services"
3 with "Identify job postings and needs/gaps"
3 "Conduct social engineering"
3 "Identify supply chains"
2 "Obfuscate infrastructure"
2 "Connect to targets of interest"
2 "Determine 3rd party infrastructure services"
2 "Compromise 3rd party infrastructure to support delivery"
2 "Acquire or compromise 3rd party signing certificates"
3 "Acquire OSINT data sets and information"
2 "Acquire and/or use 3rd party software services"
2 "Dynamic DNS"

**Comment by Delta-Sierra** [comment]
In fact the duplicates come mitre/cti repository; they have distinct uuids (and even distinct descriptions).  
It seems quite a painful task to try to handle all these cases in the generation script (will have to "choose" between the uuids, to merge the descriptions... Not to mention new duplicates that may appear in the future).
Maybe the best idea would be to report this issue [there](https://github.com/mitre/cti/issues)? If it is okay with you I will do it.

**Comment by Delta-Sierra** [comment]
Update/Reminder:
Will update the scripts to append external_id to value strings.

**Comment by Delta-Sierra** [comment]
Should be fixed by #181
Can you confirm?

**Comment by Rafiot** [comment]
Yep, all good, thank you :)
