### ISSUE TITLE
Duplicate (Igexin) in the android cluster

### ISSUE THREAD

**Issue by Rafiot** [MISP/misp-galaxy#183]
Should these two be merged? 

https://github.com/MISP/misp-galaxy/blob/master/clusters/android.json#L2122
https://github.com/MISP/misp-galaxy/blob/master/clusters/android.json#L4280

**Comment by Delta-Sierra** [comment]
Indeed I made a mistake because of the synonym (that I also forgot to add...). My b
ad!
Should be fixed now! Thanks for pointing it! :)

**Comment by Rafiot** [comment]
All good, thanks!
