### ISSUE TITLE
Add CFR.org metadata into the galaxy

### ISSUE THREAD

**Issue by adulau** [MISP/misp-galaxy#232]
Add CFR.org metadata into the galaxy such as:

- suspected-victims
- type-of-incident -> Espionage
- suspected-state-sponsor -> Country code (to review with country)
- target-category -> Government, Civil society, Private sector
- victim-government-reaction -> Yes/No/Unknown
- policy-response -> Criminal charges
- suspected-state-sponsor-response -> Denial

https://www.cfr.org/interactive/cyber-operations/pla-unit-61398

**Comment by SteveClement** [comment]
bump @Delta-Sierra

**Comment by adulau** [comment]
This was done and it should be up-to-date.
