### ISSUE TITLE
duplicate entries within the galaxies

### ISSUE THREAD

**Issue by cvandeplas** [MISP/misp-galaxy#27]
With more an more galaxies appearing more and more duplicate entries appear in the different galaxies. 
This leads to inconsistency in the labeling of the data and confusion of the user.

Examples:
- galaxy ransomware: Cryptowall, Locky
- galaxy tool: Cryptowall, Locky

I believe these issues should be tackled before merging pull-requests.

This issue is also for talking about:
- for what things do we want to create new galaxies?
- finding solutions to move entries tagged in an old galaxy to the new one. For example: "tool:locky" to "ransomware:locky"

**Comment by adulau** [comment]
The tool cluster was a generic created before we had more contributions with specific clusters.

So the idea is to remove from Tool that the ones that already exist in a specific cluster like ransomware. As this is a chicken or the egg dilemma, we prefer to have already the new cluster ready than waiting eternally. So feel free to update tool following the new ransomware cluster. The idea for the ransomware cluster is to generate it automatically from the CSV export.

**Comment by adulau** [comment]
Maybe we should find a nice sponsor that would support an extension within MISP core to do mass translation of tags and galaxy ;-)

**Comment by iglocska** [comment]
I can't see the "hint hint nudge nudge" in your message, @adulau
