### ISSUE TITLE
Malware Families Galaxy - based on Malpedia data

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/misp-galaxy#275]
Source: https://malpedia.caad.fkie.fraunhofer.de/

Waiting for authorization :angel: 
https://twitter.com/adulau/status/1048142123726454784

**Comment by garanews** [comment]
https://github.com/MISP/misp-galaxy/pull/277

**Comment by dadokkio** [comment]
Hi, me and  @garanews were working on the same topic, so some code has been already done.
It's based on a local clone of malpedia repo and we are adding an update function to keep the repo and the galaxy aligned.

**Comment by adulau** [comment]
Looks very good. We will merge it. @Delta-Sierra will have a look at the related field between the Threat-Actor clusters and the Malpedia galaxy. Thanks a lot for the contribution!

**Comment by adulau** [comment]
We also need to sync at regular interval  and we need to work on that somehow ;-)

**Comment by danielplohmann** [comment]
Hey!

We have used the code pushed to the tools folder of this repo to implement the generation/update methodology of the Malpedia galaxy cluster on our side.
This means with every update to Malpedia, a most recent version is automatically generated and can now be easily fetched through our REST API, including versioning of the galaxy cluster:

https://malpedia.caad.fkie.fraunhofer.de/api/get/misp

We have added the initial set of UUIDs for the galaxy and families you had already generated to ensure forward-compatibility.

As soon as you have decided how to link in the actor information (cc @Delta-Sierra), just let us know about that and we will happily integrate that as well!

Best Regards

Daniel Plohmann / Steffen Enders

**Comment by danielplohmann** [comment]
The file format should now be consistent without duplicate URLs, we also added the "category: tool" that was lately introduced.
What we haven't included on our site (yet?) are the automagically added relationships that were introduced 1-2 weeks ago. Do you want to generate and add these after pulling updates from us?
Additionally, we have introduced 

https://malpedia.caad.fkie.fraunhofer.de/api/get/version

Which returns date and version (based on commit) for quick lookups of potential updates of malpedia.

**Comment by Rafiot** [comment]
@danielplohmann there are a few duplicate values in the galaxies:

2 ('Malpedia', 'Cpuminer')
4 ('Malpedia', 'X-Agent')
3 ('Malpedia', 'DualToy')
3 ('Malpedia', 'Mokes')
2 ('Malpedia', 'WireLurker')
2 ('Malpedia', 'Wirenet')
3 ('Malpedia', 'FlexiSpy')
2 ('Malpedia', 'Bahamut')
2 ('Malpedia', 'Crisis')
2 ('Malpedia', 'Erebus')
2 ('Malpedia', 'Lazarus')
2 ('Malpedia', 'Mirai')
2 ('Malpedia', 'Retefe')
2 ('Malpedia', 'Uroburos')
2 ('Malpedia', 'Winnti')


I'm not sure if it is expected on your side, but for MISP, the tag for all the entries will be the same and it won't be possible to differentiate them.

**Comment by danielplohmann** [comment]
Ah, Isee.
That's a result of the same family existing for multiple platforms. 
I would propose to change it in a way, that in those cases the platform will be added in brackets behind the name, e.g. X-Agent (Win) and X-Agent (OS X) etc. 
For malpedia, this was not necessary as we have native platform prefixes for all family names and platform indicator icons along the common names, which are used as tags for MISP.

Would that work?

**Comment by Rafiot** [comment]
Yep, that would work :)

**Comment by danielplohmann** [comment]
Name deconfliction for families with presence on multiple platforms is now implemented in the REST API Call: https://malpedia.caad.fkie.fraunhofer.de/api/get/misp

**Comment by adulau** [comment]
@danielplohmann Thank you very much for the updates. Malpedia galaxy is now updated to the latest version.
