### ISSUE TITLE
Inconsistent naming of countries in threat_actors

### ISSUE THREAD

**Issue by netjinho** [MISP/misp-galaxy#339]
What is the ISO followed by the threat_actors file in clusters? ISO3166?

Sometimes, there are names like "Russia" or like "Russian Federation".

Shouldn't it be using the same name or convert everything to ISO 3166-1 alpha 2?

**Comment by Delta-Sierra** [comment]
If I'm not mistaken "Russian Federation" only appears in information taken from https://www.cfr.org/ (the attributes prefixed with "cfr-") to be consistent with the source.
(For instance, both "Russia" and "Russian Federation" appear on [Cloud Atlas](https://www.cfr.org/interactive/cyber-operations/cloud-atlas) page, so both appear in the galaxy)

In every other case "Russia" is the one we usually use.

**Comment by netjinho** [comment]
That's what I thought, although "Russia" appears in "cfr-suspected-victims", so it seems that inside the "cfr-*" information there are no standard way to display country names as well. Despite this, the "country" field is represented according to ISO 3166-1 alpha 2, so there is no consistency in general.
