### ISSUE TITLE
Few utf8 chinese issues

### ISSUE THREAD

**Issue by Th4nat0s** [MISP/misp-galaxy#34]
find -name "*.json" -exec iconv -f UTF-8 {} -o /dev/null \;
iconv: illegal input sequence at position 499
iconv: illegal input sequence at position 2178
iconv: illegal input sequence at position 479
iconv: illegal input sequence at position 500
iconv: illegal input sequence at position 6374

$./chk_dup.py 
Json load error in threat-actor.json
Json load error in tool.json
Json load error in preventive-measure.json
Json load error in microsoft-activity-group.json
Json load error in ransomware.json

Example in ransom
    "description": "my-Little-Ransomware; AES(128); .已加密 .encrypted; ",
     "description": "my-Little-Ransomware; AES(128); .已[m~J.[m~F .encrypted; ",
    2e e5  b7 b2 e5 8a a0 e5 af 86 

Any correction recommendation ...   ?? What is the file encoding supposed to be ??

**Comment by Th4nat0s** [comment]
Mwell... 

Unicode seems ok at least in console, and vim, seems python3 json.load related pbm... will try to force the encode since no bom are present...

**Comment by Rafiot** [comment]
Unicode should be good. I'm not sure if you solved the problem or not ;)

**Comment by Th4nat0s** [comment]
well not... maybe you can help me :) 

python2 is ok...
data.append(json.load(open("%s/%s" % (path, jfile))))

same in python 3.. hang...Ascii  of course is not unicode...
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 499: ordinal not in range(128)

I tried a "pénible" things like that : 
data.append(json.loads(open("%s/%s" % (path, jfile)).read().encode('utf-8')))

Stuck on same error ....  Help apreciated...

**Comment by Rafiot** [comment]
This snippet works fine for me: 

```
$  ipython3
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import json

In [2]: data = []

In [3]: data.append(json.load(open('foo.json')))

In [4]: data
Out[4]: [{'description': 'my-Little-Ransomware; AES(128); .已[mJ.[mF .encrypted; '}]
```

And I can run `chk_dup.py` in HEAD fine. Can you do a PR with something that fails?

**Comment by Th4nat0s** [comment]
Amazing .... I'm stuck on the "in git" ransomware file : 

$md5sum clusters/ransomware.json 
6e95f4b0bc57426abaf9da36bbef1ae0  clusters/ransomware.json

>>> import json
>>> data = []
>>> data.append(json.load(open('./clusters/ransomware.json')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.2/json/__init__.py", line 261, in load
    return loads(fp.read(),
  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 6374: ordinal not in range(128)

Json module     2.0.9
python  3.2.3

**Comment by Rafiot** [comment]
python 3.2 is full of badness. You should at least use python 3.4 (afaik, it is on ubuntu 14.04). 3.2 is super old and deprecated.

**Comment by Th4nat0s** [comment]
LTS Debian 7 (Usable up to may 2018) Is running 3.2 SIR :) ... The good news is that the problem does  seems to come from my mistakes :)...  ( No Distrib Troll Please ).

**Comment by Rafiot** [comment]
Okay, Debian *old* stable... :p 
I don't blame you, you could be using Cent OS.

**Comment by Th4nat0s** [comment]
Well, Hopefully I don't use the most "used" and "compatible" platform with MISP :) 
Anyway, I do confirm, after a long dist-upgrade.. the json load work !...

**Comment by Rafiot** [comment]
Wait a second... Which file are you using? The last update of the ransomware in the repository has been updated 19 days ago.

**Comment by adulau** [comment]
I assume we can close this one with "too old version of Python 3" ;-)

**Comment by Rafiot** [comment]
Nope, the last snippet uses python 3.4, but I have no idea what is in the file.

**Comment by SteveClement** [comment]
Testing with Debian 8 and will close if that works on python 3.4

**Comment by SteveClement** [comment]
Looks working to me.

```bash
misp@misp-vm:~/misp-galaxy$ cd clusters/
misp@misp-vm:~/misp-galaxy/clusters$ python3
Python 3.4.2 (default, Sep 25 2018, 22:02:39) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.load(open('ransomware.json'))
{'type': 'ransomware', 'uuid': '10cf658b-5d32-4c4b-bb32-61760a640372', 'values': [{'uuid': '81b4e3ac-aa83-4616-9899-8e19ee3bb78b', 'description': 'This is most likely to affect English speaking users, since the note is written in English. English is understood worldwide, thus anyone can be harmed. The hacker spread the virus using email spam, fake updates, and harmful attachments. All your files are compromised including music, MS Office, Open Office, pictures, videos, shared online files etc..', 'value': 'Nhtnwcuf Ransomware (Fake)', 'meta': {'refs': ['https://id-ransomware.blogspot.co.il/2017/03/nhtnwcuf-ransomware.html'], 'date': 'March 2017', 'ransomnotes':
.....

```
