### ISSUE TITLE
Possible update to cluster tool.json (Xbash)

### ISSUE THREAD

**Issue by alinamd** [MISP/misp-galaxy#348]
I would like to propose the following update to the tool.json cluster specifically regarding xbash: 

update description to:
"description": "Xbash is a malware family that is targeting Linux and Microsoft Windows servers. We can tie this malware, which we have named Xbash, to the Iron Group, a threat actor group known for previous ransomware attacks. Xbash was developed using Python and converted into self-contained Linux ELF executables by abusing the legitimate tool PyInstaller for distribution. Xbash aimed on discovering unprotected services, deleting victim’s MySQL, PostgreSQL and MongoDB databases, and ransom for Bitcoins. Linux based systems are targeted for ransomware and botnet capabilities. The ransomware targets and deletes linux databases and there is no evidence of any functionality that makes recovery even possible by payment the ransom. Where as, windows based systems are targeted for coinmining & self-propagating capabilities. Xbash spreads by attacking weak passwords and unpatched vulnerabilities.",

add the following refs:
https://unit42.paloaltonetworks.com/unit42-xbash-combines-botnet-ransomware-coinmining-worm-targets-linux-windows/

**Comment by adulau** [comment]
Thank you. Fixed in https://github.com/MISP/misp-galaxy/commit/f7367ef887915d13a6353406f80ed4720a911b67
