### ISSUE TITLE
All galaxies need to be updated with a kill_chain_order

### ISSUE THREAD

**Issue by RichieB2B** [MISP/misp-galaxy#349]
Because of 6210f27c0d86ea6732646eee1a96075d52ee95fc all galaxy definitions now need a kill_chain_order, otherwise they will not load. See https://github.com/MISP/MISP/issues/4198

**Comment by RichieB2B** [comment]
Fixed in https://github.com/MISP/MISP/commit/3718a89b9a2ffa81c313de18c08b590c61a9e44d
Thanks!

**Comment by adulau** [comment]
Thank you for your sharp eye. Enjoy your weekend.
