### ISSUE TITLE
can't found AGENT.DNE 

### ISSUE THREAD

**Issue by Th4nat0s** [MISP/misp-galaxy#35]
@iglocska Do you have any info on this one ?? In tools.json. I Can't found any "serious" report on it.

**Comment by adulau** [comment]
If I recall properly (only from the official public discussion and out of any secret club discussions), it was the parent or // of Agent.BTZ:

https://www.virusbulletin.com/uploads/pdf/conference_slides/2015/Baumgartner-VB2015.pdf (Page 12)

I suppose this KS presentation can be considered as a "serious" report.

**Comment by Th4nat0s** [comment]
Serious but light in Documentation...

Will investigate (in public clubs:) Since I got a start now...

**Comment by Th4nat0s** [comment]
https://securelist.com/blog/research/72081/satellite-turla-apt-command-and-control-in-the-sky/
http://media.kaspersky.com/pdf/SatTurla_Solution_Paper.pdf

Backdoor.Win32.Turla.cd
Backdoor.Win32.Turla.ce
Backdoor.Win32.Turla.cl
Backdoor.Win32.Turla.ch
Backdoor.Win32.Turla.cj
Backdoor.Win32.Turla.ck
Trojan.Win32.Agent.dne


plenty with 2 words to serach :)
