### ISSUE TITLE
Adding new threat actors to the galaxies

### ISSUE THREAD

**Issue by Kradma** [MISP/misp-galaxy#354]
# Adding new threat actors to the galaxies

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | centOS
| OS version (client)       | Ubuntu
| PHP version               | 5.6
| MISP version / git hash   | 2.4.101
| Browser                   | If applicable

### Current problem
We have detected that some threat actors from Mitre Attack are missing and we would like to add them to our current galaxies. Is there any way to do that?

Thanks in advance.

**Comment by SteveClement** [comment]
Dear @Kradma 

I transferred the issue to the misp-galaxy repository.

So what would be next is fork this repository, then you make the changes of what is missing and send us a PR.

**Comment by adulau** [comment]
I think we can close it as both have their own galaxy cluster with specific relationships.  If you think this should be reopen, feel free.
