### ISSUE TITLE
Adding / Removing Custom Galaxies

### ISSUE THREAD

**Issue by LabyrINTh-Jim** [MISP/misp-galaxy#360]
Yo yo yo!
Jimbo from the "D" again - 

So the taxonomies are coming out just fine. 

Moving on to galaxies. 

I was told that I need to place the galaxy data into two separate spots. 
I used this reference to make an educated guess as to where: 
https://www.misp-project.org/misp-training/3.2-misp-galaxy.pdf

My galaxy file was named test-galaxy.json

I placed this file into both the ./galaxy folder and the ./cluster folder

My ./galaxy folder .json looked like this:

{
    "name": "TEST GALAXY",
    "type": "test-galaxy",
    "description": "This galaxy is to confirm that you can make test galaxies",
    "version": 1,
    "uuid": "5855933e-45e6-11e9-b210-d663bd873d93"
}

My ./clusters folder .json looked like this:

{
	"description": "threat-actor-tools is an enumeration of tools used by adversaries. The list includes malware but also common software regularly used by the adversaries.",
	"type": "tool",
	"version": 1,
	"name": "test-cluster",
	"uuid": "623555c8-45ec-11e9-b210-d663bd873d93",
	"authors": "James Palazzolo - LabyrINTh CIS",
	"source": "MISP Project",
	"values": [{
		"description": "Test Value",
		"meta": {
			"refs": [
				"https://thehackernews.com/search/label/Zusy%20Malware",
				"http://blog.trendmicro.com/trendlabs-security-intelligence/the-tinbatinybanker-malware/"
			],
			"synonyms": [
				"Test Value",
				"Testaroo",
				"TinyTester"
			],
			"uuid": "9cccfede-45ec-11e9-b210-d663bd873d93",
			"value": "Test Galaxy Value"
		}
	}]
}

Both files passed through jsonlint and I could have sworn I was following the schema correctly...
MISP did recognize the galaxy:

![image](https://user-images.githubusercontent.com/47990276/54324781-78e2f080-45d5-11e9-8765-31b21c3b4c82.png)

However, I now have two issues. 

First issue:  I removed the .json file from both ./galaxy folder and the ./clusters folder.  When I hit update galaxies it's still there lol...

![image](https://user-images.githubusercontent.com/47990276/54324815-a2038100-45d5-11e9-9005-bb93efa8e542.png)

How do I purge this from the list?

Second issue:  it recognized the galaxy but none of the cluster information was attributed over and so the galaxy values were empty.  What am I doing wrong here?

I'm sure it's something simple - 

Jimbo

**Comment by LabyrINTh-Jim** [comment]
By the way - Friday can't get here soon enough lol.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/42e1777a50afb4ff2716c011aeb2a54d88d089e5 - Thank you for the notification.
