### ISSUE TITLE
Merge duplicated groups

### ISSUE THREAD

**Issue by chrisdoman** [MISP/misp-galaxy#39]
I think these might be duplicates?

Lotus Blossom and Lotus Panda

**Comment by SteveClement** [comment]
Thanks for reaching out.

Reading this:

https://www.crowdstrike.com/blog/rhetoric-foreshadows-cyber-activity-in-the-south-china-sea/ (Lotus Panda)

And those: (Lotus Blossom)

https://www.paloaltonetworks.com/resources/research/unit42-operation-lotus-blossom.html
https://attack.mitre.org/groups/G0030/

Would suggest that they want to be handled seperate ATM.
