### ISSUE TITLE
Add more items for misp-galaxy:financial-fraud

### ISSUE THREAD

**Issue by Gudmo** [MISP/misp-galaxy#466]
Please consider adding the following items for the misp-galaxy:financial-fraud

fraud-tactics:Perform Fraud:Investment Fraud
fraud-tactics:Perform Fraud:Romance Scam
fraud-tactics:Perform Fraud:Buying/Renting Fraud
fraud-tactics:Perform Fraud:Cash Recovery Scam
fraud-tactics:Perform Fraud:Fake Invoice Fraud

**Comment by adulau** [comment]
Fixed in 77605f8d432a389a180e18033c51235dcc8b87a5.

Thank you for the contribution!
