### ISSUE TITLE
What is the related field in clusters used for?

### ISSUE THREAD

**Issue by cxmplex** [MISP/misp-galaxy#511]
Hello,

My company is working on a custom galaxy for our use-case. In creating the cluster, I've noticed a "related" field which usually includes a key:value pair from the taxonomy. However, in the UI, I do not see where this value is used.

I believe it's probably used for some internal mapping, can you clarify the purpose of it?

**Comment by adulau** [comment]
We have a set of galaxy/clusters with related threat-actor or alike. This is currently not used in MISP but it will be in a future release. The data "related" is maintained and already used in some other tools using the MISP galaxy. Feel free to use those. The related field is public.
