### ISSUE TITLE
Provide consistent UUID types

### ISSUE THREAD

**Issue by rhaist** [MISP/misp-galaxy#545]
While building a strict parser and linter for the galaxies I noticed that some UUIDs are Type 1 and some Type 4.

Example for Type 1:
https://github.com/MISP/misp-galaxy/blob/master/clusters/threat-actor.json#L5797

Example for Type 4:
https://github.com/MISP/misp-galaxy/blob/master/clusters/threat-actor.json#L82

I think this is a mistake and the original authors intended all UUIDs to be of true random origin?

Reference: [Online Decoder Tool](https://realityripple.com/Tools/UnUUID/)

**Comment by Rafiot** [comment]
We accept every type of UUIDs, your linter should accept that.

**Comment by adulau** [comment]
UUID version 4 are just recommended.  All good then.

~~~
UUID version 4 is RECOMMENDED when assigning it to a new object reference and MUST be present. 
~~~
