### ISSUE TITLE
Threat Actors: Conflict between "Operation C-Major" and "HummingBad"

### ISSUE THREAD

**Issue by danielplohmann** [MISP/misp-galaxy#60]
actor "HummingBad" has synonym "Operation C-Major", but "Operation C-Major" is also a key of its own (without "HummingBad" as synonyms, so there is an asymmetry in naming).

I was also not able to find any documentation that indicates a connection between "HummingBad" and "Operation C-Major", so I would propose to delete that synonym for "HummingBad" and treat them individually.

**Comment by adulau** [comment]
Thank you for the feedback. This should be fixed.
