### ISSUE TITLE
Json stating APT30 as Naikon while further down it states they are seperate threat actors

### ISSUE THREAD

**Issue by Argonyte** [MISP/misp-galaxy#611]
The Threat Actor Json has a error where it shows that APT30 is Naikon threat group. Going further down the file it also shows APT30 has similarities with Naikon, but it isn't Naikon. 

![FireShot Capture 065 - misp-galaxy_threat-actor json at main · MISP_misp-galaxy - github com](https://user-images.githubusercontent.com/54732393/102011431-e63c2c00-3d3b-11eb-8c92-435fb5a17aec.png)
![FireShot Capture 068 - misp-galaxy_threat-actor json at main · MISP_misp-galaxy - github com](https://user-images.githubusercontent.com/54732393/102011434-eb00e000-3d3b-11eb-9b0d-6f53d3d172de.png)

**Comment by r0ny123** [comment]
So, what is it you propose to tackle this issue? PR's are welcome.

**Comment by sebdraven** [comment]
If Naikon is not APT30, it will be fine to delete the references like https://www.cfr.org/interactive/cyber-operations/apt-30 or https://www.cfr.org/interactive/cyber-operations/apt-30 ?
