### ISSUE TITLE
MITRE ATT&CK Tactics missing new Pre-ATT&CK tactics.

### ISSUE THREAD

**Issue by brandonbullen** [MISP/misp-galaxy#689]
With ATT&CK v8, the pre-ATT&CK tactics were removed and replaced with two additional tactics, Reconnaissance and Resource Development.
These are currently missing from the MISP MITRE Tactics galaxy.

Current Matrix:
https://attack.mitre.org/versions/v10/

Release in which pre-ATT&CK was replaced:
https://github.com/mitre/cti/releases/tag/ATT%26CK-v8.0

Could we please update this Galaxy to include these?

**Comment by cvandeplas** [comment]
this was already addressed
