### ISSUE TITLE
Add Slack support to the repo

### ISSUE THREAD

**Issue by stephane81** [MISP/misp-galaxy#696]
Not an issue but I would like to get notifications on Slack when PRs are opened/merged. 

It requires Slack support to be added: https://github.com/apps/slack

If you think it's useful, I would be one of the first to use it.

**Comment by cvandeplas** [comment]
Hi, to my understanding this is something you have to enable on your own account. 
See https://github.com/integrations/slack

**Comment by stephane81** [comment]
Hi,
It's enabled on my account, and I can follow another repo. 

From the link below, it seems that one can only subscribe to a repository if the owner of that repository has installed the [Slack app on GitHub](https://github.com/apps/slack), which sends GitHub activity to Slack.

https://github.com/integrations/slack/issues/454

**Comment by adulau** [comment]
I don't mind to add read-only apps to the repos but when an application asks for write access for pushing notification out. It's weird...

![write-access](https://user-images.githubusercontent.com/3309/160703556-d3a829fa-d235-41aa-ad0d-abcf58b2d575.png)

**Comment by stephane81** [comment]
I see ... thanks for looking into it 😄 

<img width="827" alt="image" src="https://user-images.githubusercontent.com/12708874/161039339-d1565f44-6ec1-4a06-a1a6-8a0972fb6840.png">
https://github.com/integrations/slack/blob/939af1c7d0df1635ab1594444883c76e5c9ad1db/README.md

**Comment by adulau** [comment]
If you see another way to do it properly, let me know. I'll close the issue.
