### ISSUE TITLE
New source 360

### ISSUE THREAD

**Issue by adulau** [MISP/misp-galaxy#764]
https://apt.360.net/aptlist

**Comment by cvandeplas** [comment]
![image](https://user-images.githubusercontent.com/1073662/189996687-0f3a137e-b036-4f34-9c29-de98494bb477.png)

**Comment by cvandeplas** [comment]
hmm, some fixes are needed.

**Comment by cvandeplas** [comment]
work ongoing in https://github.com/MISP/misp-galaxy/pull/767

**Comment by adulau** [comment]
Thanks a lot!
