### ISSUE TITLE
MITRE mobile outdated

### ISSUE THREAD

**Issue by nyx0** [MISP/misp-galaxy#773]
Hello, would it be possible to update MITRE's galaxy please.
Techniques like [T1624](https://attack.mitre.org/techniques/T1624/) are not present. I would like to contribute but I would assume you have some script to generate MISP galaxy based on MITRE website or else.

**Comment by cvandeplas** [comment]
Hi, indeed, I have just moved the script that was a bit difficult to find from subfolders to the `tools` folder. 

I also used the opportunity to generate the latest v11.3 version of MITRE ATT&CK. See commit https://github.com/MISP/misp-galaxy/commit/e259458d5ae29c360950779bca7deb065197d160
