### ISSUE TITLE
Creating galaxies in MISP

### ISSUE THREAD

**Issue by eagerwolverine** [MISP/misp-galaxy#836]
Can anyone please help me on how I create my custom galaxies on MISP platform where I have the directory as "misp@misp" on oracle virtual box setup using misp instance virtual image.

Please help!!

Thank you in advance!

**Comment by cudeso** [comment]
Hello @eagerwolverine , maybe this post can already help you: https://www.misp-project.org/2020/07/31/MISP-galaxy-101.html/
