### ISSUE TITLE
Creating custom galaxies in MISP

### ISSUE THREAD

**Issue by rajdeep-s45** [MISP/misp-galaxy#837]
Can anyone please help in knowing that how can I create my custom galaxies on MISP platform.

I've setup my MISP platform on the oracle vm virtualbox and I need to create custom galaxies on it... But I am not able to..

The current directory where I log in Virtual box is "misp@misp" so kindly please help.

Thank you in advance..!

**Comment by adulau** [comment]
You can have a look at the training materials -> https://www.misp-project.org/misp-training/3.2-misp-galaxy.pdf

**Comment by rajdeep-s45** [comment]
I've read the documentation.. I'm just not able to figure out what should be the proper directory for this virtual machine created above.
