### ISSUE TITLE
Turla and APT26 share the same synonym

### ISSUE THREAD

**Issue by frenkiesp** [MISP/misp-galaxy#942]
Hello,
We noticed that the threat actors Turla and APT26 share the same alias/synonym "Hippo Team". How is this possible? Is this a mistake? 
Thanks.
Francesco

**Comment by adulau** [comment]
Thanks for the notification, it's now fixed.

**Comment by frenkiesp** [comment]
Hi Alexandre,
thanks for the fix. We found other six cases that have this issue. I attached a CSV file
[misp_shared_aliases.csv](https://github.com/MISP/misp-galaxy/files/14556614/misp_shared_aliases.csv)

Tanks a lot,
Francesco

**Comment by adulau** [comment]
Thanks for the CSV and I just quickly reviewed those:

- [ ] PLA Navy is more the sponsoring organisation.  We should move it in a meta on the three clusters like `sponsor-organisation`
- [X] Grizzly Steppe is correct to be a synonym for APT28 and APT29
- [X] Andariel is a sub-group of Lazarous group
- [X] Cobalt Gypsy seems to be correct as it's historical with a discovery of multiple IR-sponsored groups
- [X] Golden Chickens seems to be a generic group to describe group 01 and 02 globally
