### ISSUE TITLE
Add the Microsoft galaxy "Threat Matrix for Storage Services "

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-galaxy#947]
From https://microsoft.github.io/Threat-matrix-for-storage-services/

**Comment by cvandeplas** [comment]
Raw data is located here: https://github.com/microsoft/Threat-matrix-for-storage-services/tree/main

At first sight it looks similar to the Azure Threat Research Matrix, so the `tools/gen_atrm.py` script might be a good source of inspiration to generate this Galaxy.

**Comment by cvandeplas** [comment]
I've raised a[ feature request](https://github.com/microsoft/Threat-matrix-for-storage-services/issues/2) for having some uniformity at Microsoft. :-)

**Comment by cvandeplas** [comment]
New initial galaxy/cluster added in the [`tools/gen_ms_tmss.py`](https://github.com/MISP/misp-galaxy/blob/main/tools/gen_ms_tmss.py) script. 
The script is pushed to the repo, but not the galaxy/cluster yet.
There might be value in refactoring some things to merge the Microsoft Galaxies together in one `microsoft` namespace, although I'm not sure about the impact. What are your thoughts? 


![image](https://github.com/MISP/misp-galaxy/assets/1073662/1228be68-384b-4f31-9513-368a750920c7)

Includes also the relations to MITRE ATT&CK Attack Patterns:
![image](https://github.com/MISP/misp-galaxy/assets/1073662/4af31d5a-92db-4f94-b112-0783b3de7136)

**Comment by cvandeplas** [comment]
As discussed, changed the namespace to Microsoft
